Documentation

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,4 +1,4 @@
-# Before being able to push to my .github\workflows directories, 
+# Before being able to push to my .github\workflows directories,
 # I had to create a new personal token with workflow enabled at https://github.com/settings/tokens
 
 # This is the name of the workflow, visible on GitHub UI.
@@ -8,25 +8,21 @@ on: [push]
 jobs:
   build:
     name: ${{ matrix.arduino-boards-fqbn }} - test compiling examples
-    
+
     runs-on: ubuntu-latest # I picked Ubuntu to use shell scripts.
-    
-    env: 
-      # Space separated list with or without double quotes around the list. 
-      # If you need a libraries with a space in its name like Adafruit NeoPixel or Adafruit INA219
-      # You MUST put each library in one line and use double quotes at least for the library with a space in its name.
-      REQUIRED_LIBRARIES: 
-        Servo
-        "ESP32Servo"
-        "Adafruit NeoPixel"
-      REQUIRED_LIBRARIES1:
-              
+
+    env:
+      # Space separated list without double quotes around the list. 
+      # If you need a library with a space in its name, like Adafruit NeoPixel or Adafruit INA219, you must use double quotes
+      # around the name and have at least 2 entries, where the first must be without double quotes! You may use Servo as dummy entry.
+      REQUIRED_LIBRARIES: Servo "Adafruit NeoPixel"
+
       # Output colors
       RED: '\033[0;31m'
       GREEN: '\033[0;32m'
       YELLOW: '\033[1;33m'
       BLUE: '\033[0;34m'
-      
+
     strategy:
       matrix:
         # The matrix will produce one job for each configuration parameter of type `arduino-boards-fqbn`
@@ -44,27 +40,25 @@ jobs:
           - ATTinyCore:avr:attinyx5:chip=85,clock=1internal
 
         # Choose the right platform for the boards we want to test. (maybe in the future Arduino will automatically do this for you)
-        # This works like this: when the fqbn is "arduino:avr:uno" the variable `platform` is set to "arduino:avr". 
+        # This works like this: when the fqbn is "arduino:avr:uno" the variable `platform` is set to "arduino:avr".
         # Just take the first 2 token of the fqbn - this cannot be automatically done by GitHub workflow :-(
         #############################################################################################################
         include:
           - arduino-boards-fqbn: digistump:avr:digispark-tiny1  # ATtiny85 board @1 MHz
             platform: digistump:avr
             # examples-build-properties / aka setting compiler.cpp.extra_flags does not work for digistump:avr platform
-            examples-exclude: "WhistleSwitch Test" # Space separated list of (unique substrings of) example names to exclude in build
-            
+            examples-exclude: WhistleSwitch Test # Space separated list of (unique substrings of) example names to exclude in build
+
           - arduino-boards-fqbn: ATTinyCore:avr:attinyx5:chip=85,clock=1internal
             platform: ATTinyCore:avr
-            examples-exclude: 
-              WhistleSwitch 
-              "Test" # Space separated list of (unique substrings of) example names to exclude in build
+            examples-exclude: WhistleSwitch "Test" # Space separated list of (unique substrings of) example names to exclude in build
             examples-build-properties:
               SimpleFrequencyDetector:
                 -DDEBUG
                 -DINFO
               WhistleSwitch:
                 -DDEBUG
-                
+
           - arduino-boards-fqbn: arduino:avr:uno
             platform: arduino:avr
             SimpleFrequencyDetector: -DDEBUG
@@ -72,13 +66,13 @@ jobs:
             examples-build-properties:
               WhistleSwitch:
                 -DDEBUG
-            
+
       # Do not cancel all jobs / architectures if one job fails
       fail-fast: false
 
     # This is the list of steps this job will run.
     steps:
-    
+
           #######################################
           #MATRIX="${{ toJson(matrix) }}"
           #echo MATRIX="$MATRIX" # Multi line output
@@ -86,7 +80,7 @@ jobs:
           #echo matrix=$matrix   # empty
           #echo matrix=${{ matrix }} #=Object The string "Object"
           #########################################
-          
+
       # First of all, we clone the repo using the `checkout` action.
       - name: Checkout
         uses: actions/checkout@master
@@ -97,47 +91,47 @@ jobs:
         uses: arduino/setup-arduino-cli@v1.0.0
 
       #- name: Cache Arduino packages
-      # does not work, since we can not build separate caches for each platform 
+      # does not work, since we can not build separate caches for each platform
       #  id: arduino15-packages-env.MATRIX_PLATFORM <- This is a syntax error and this too: arduino15-packages-${{ matrix.platform }}
       #  uses: actions/cache@v1 # using version 1
       #  with:
       #    path: $HOME/.arduino15/packages/
       #    key: arduino15-packages-env.MATRIX_PLATFORM
-      
+
       - name: Dump variables
         env:
+          REQUIRED_LIBRARIES_ENV: ${{ env.REQUIRED_LIBRARIES }}
           EXAMPLES_EXCLUDE: ${{ toJson(matrix.examples-exclude) }} # the content as string in double quotes with escaped double quotes if one token contains one
-          REQUIRED_LIBRARIES_ENV: ${{ env.REQUIRED_LIBRARIES }}      
         run: |
           echo "matrix.examples-build-properties=${{ toJson(matrix.examples-build-properties) }}"
-          
-          
-          echo -e "\n\nREQUIRED_LIBRARIES test"
+
+
+          echo -e "\n\nREQUIRED_LIBRARIES test\n"
           # here all quotes are escaped leading to have "Adafruit NeoPixel" or 'Adafruit NeoPixel' as 2 tokens each
           echo \$REQUIRED_LIBRARIES=$REQUIRED_LIBRARIES
           echo REQUIRED_LIBRARIES array=
           for word in $REQUIRED_LIBRARIES; do
             echo $word
           done
-          
-          # here all quotes are escaped leading to have "Adafruit NeoPixel" or 'Adafruit NeoPixel' as 2 tokens each
+
+          # give the same results as with REQUIRED_LIBRARIES
           echo \$REQUIRED_LIBRARIES_ENV=$REQUIRED_LIBRARIES_ENV
           echo REQUIRED_LIBRARIES_ENV array=
           for word in $REQUIRED_LIBRARIES_ENV; do
             echo $word
           done
-          
+
           # This gives one line "Adafruit NeoPixel" as one token and the line Adafruit NeoPixel as 2 token
-          echo env.REQUIRED_LIBRARIES=${{ env.REQUIRED_LIBRARIES }} 
+          echo env.REQUIRED_LIBRARIES=${{ env.REQUIRED_LIBRARIES }}
           echo REQUIRED_LIBRARIES_ENV array=
           for word in ${{ env.REQUIRED_LIBRARIES }} ; do
             echo $word
-          done          
-          
-          echo -e "\n\nmatrix.examples-exclude test\n"
+          done
+
+          echo -e "\n\nmatrix.examples-exclude test gives 3 different results\n"
           # 2 lines (without any double quotes) WhistleSwitch + Test give for all 3 test the same results as one line WhistleSwitch Test!
-          # If we have a quoted entry at one line it is taken as one token including the quotes
-          
+          # If we have a quoted entry at one line it is taken as one array element including the quotes
+
           # 1 line WhistleSwitch Test (without double quotes) give WhistleSwitch Test as 2 token "WhistleSwitch and Test"
           # 2 lines WhistleSwitch + "Test" give "WhistleSwitch \"Test\"" and 2 token "WhistleSwitch and \"Test\""
           echo env \$EXAMPLES_EXCLUDE=$EXAMPLES_EXCLUDE # gives "WhistleSwitch Test" or "WhistleSwitch \"Test\""
@@ -145,21 +139,23 @@ jobs:
           for word in $EXAMPLES_EXCLUDE; do
             echo $word
           done
-          
-          # 1 line WhistleSwitch Test (without double quotes) give WhistleSwitch Test as 2 token WhistleSwitch and Test
+
+          # 1 line WhistleSwitch Test (without double quotes) give WhistleSwitch Test as 2 array elements WhistleSwitch and Test
           EXCLUDE=${{ toJson(matrix.examples-exclude) }} # gives WhistleSwitch Test or WhistleSwitch "Test"
           echo EXCLUDE=toJson...  =$EXCLUDE
           echo EXCLUDE=toJson...  array=
           for word in $EXCLUDE; do
             echo $word
           done
-          
-          # 1 line WhistleSwitch Test (without double quotes) give WhistleSwitch Test but as one token!
+
+          # This gives always one array element!
+          # 1 line WhistleSwitch Test (without double quotes) give WhistleSwitch Test as one array element!
+          # 2 lines WhistleSwitch + "Test" give WhistleSwitch "Test" also as one array element!
           echo toJson\(matrix.examples-exclude\)=${{ toJson(matrix.examples-exclude) }} # gives WhistleSwitch Test or WhistleSwitch "Test"
           echo toJson\(matrix.examples-exclude\) array=
           for word in ${{ toJson(matrix.examples-exclude) }}; do
             echo $word
-          done          
+          done
 
       - name: Connvert matrix to assoc array
         env:
@@ -177,7 +173,7 @@ jobs:
             echo Property of $EXAMPLE= ${PROP_MAP[$EXAMPLE]}
           fi
         shell: bash {0} # Needed to avoid an exit at first error
-                       
+
       # Here we have only the matrix values for this job i.e. only one platform and fqbn
       #{ arduino-boards-fqbn: arduino:avr:uno, platform: arduino:avr, SimpleFrequencyDetector: -DDEBUG }
       #- name: Tests
@@ -185,12 +181,12 @@ jobs:
       #    echo Test start
       #    echo Test end
       #  shell: bash {0} # Needed to avoid an exit at first error
-         
+
       - name: Link this repository as Arduino library
         run: |
           mkdir -p $HOME/Arduino/libraries
           ln -s $PWD $HOME/Arduino/libraries/.
-        
+
       - name: Install platform from build matrix
         run: |
           arduino-cli core update-index
@@ -199,7 +195,7 @@ jobs:
           arduino-cli core install ${{ matrix.platform }} # for each job / board one platform is installed
           arduino-cli board listall
           if [ ${{  matrix.platform }} == "esp32:esp32" ]; then pip install pyserial; fi
-          
+
       - name: List installed boards with their FQBN
         run: |
           arduino-cli board listall
@@ -207,19 +203,10 @@ jobs:
           # echo -e HOME=\"$HOME\" # /home/runner
           # echo PWD=$PWD # /home/runner/work/Github-Actions-Test/Github-Actions-Test
           # which arduino-cli # /opt/hostedtoolcache/arduino-cli/0.9.0/x64/arduino-cli
-          
-      - name: Install libraries
-        run: |
-          if [[ "$REQUIRED_LIBRARIES" != "" ]]; then
-            arduino-cli lib install ${{ env.REQUIRED_LIBRARIES }}
-          fi
 
-      - name: Install libraries 1
-        run: |
-          if [[ "$REQUIRED_LIBRARIES1" != "" ]]; then
-            arduino-cli lib install ${{ env.REQUIRED_LIBRARIES1 }}
-          fi
-          
+      - name: Install libraries
+        run: if [[ "$REQUIRED_LIBRARIES" != "" ]]; then arduino-cli lib install ${{ env.REQUIRED_LIBRARIES }}; fi
+
       # Finally, we compile the sketch, using the FQBN that was set in the build matrix.
       - name: Compile all examples
         env:
@@ -242,18 +229,18 @@ jobs:
                 echo -n "with ${PROP_MAP[$EXAMPLE_NAME]} "
               fi
               build_stdout=$(arduino-cli compile --verbose --warnings all --fqbn ${{ matrix.arduino-boards-fqbn }} --build-properties compiler.cpp.extra_flags="${PROP_MAP[$EXAMPLE_NAME]}" $(dirname $example) 2>&1);
-              if [ $? -ne 0 ]; then 
+              if [ $? -ne 0 ]; then
                 echo -e ""$RED"\xe2\x9c\x96" # If ok output a green checkmark else a red X and the command output.
                 exit_code=1
                 echo -e "$build_stdout \n"
-              else 
+              else
                 echo -e ""$GREEN"\xe2\x9c\x93"
-              fi 
+              fi
             fi
           done
           exit $exit_code
         shell: bash {0} # Needed to avoid an exit at first error
-        
+
       ##########################################################
-      # THIS CACHE TEST DOES NOT YET WORK  
+      # THIS CACHE TEST DOES NOT YET WORK
 
